import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/** One design token, as written in the DTCG-style JSON files. */
export interface Token {
  /** Path segments, e.g. ['color', 'bg', 'canvas']. */
  path: string[];
  /** A literal value or an alias such as "{palette.green.600}". */
  value: string | number;
  type?: string;
  description?: string;
}

const ALIAS = /^\{([^{}]+)\}$/;

function aliasTarget(value: string | number): string | undefined {
  return typeof value === 'string' ? ALIAS.exec(value)?.[1] : undefined;
}

/** Walks a DTCG document: nodes with `$value` are tokens, the rest are groups. */
export function flattenTokens(node: unknown, path: string[] = [], inheritedType?: string): Token[] {
  if (typeof node !== 'object' || node === null || Array.isArray(node)) {
    return [];
  }
  const record = node as Record<string, unknown>;
  const type = typeof record.$type === 'string' ? record.$type : inheritedType;

  if ('$value' in record) {
    const value = record.$value;
    if (typeof value !== 'string' && typeof value !== 'number') {
      throw new Error(`Token "${path.join('.')}" has an unsupported $value`);
    }
    const description = typeof record.$description === 'string' ? record.$description : undefined;
    return [{ path, value, type, description }];
  }

  return Object.entries(record)
    .filter(([key]) => !key.startsWith('$'))
    .flatMap(([key, child]) => flattenTokens(child, [...path, key], type));
}

/** Reads every `*.json` file of a folder and fails on duplicated token names. */
export function loadTokens(directory: string): Token[] {
  const files = readdirSync(directory)
    .filter((file) => file.endsWith('.json'))
    .sort();
  const tokens = files.flatMap((file) =>
    flattenTokens(JSON.parse(readFileSync(join(directory, file), 'utf8'))),
  );

  const seen = new Set<string>();
  for (const token of tokens) {
    const name = token.path.join('.');
    if (seen.has(name)) {
      throw new Error(`Duplicate token: ${name}`);
    }
    seen.add(name);
  }
  return tokens;
}

export function cssVarName(path: readonly string[]): string {
  return `--gyde-${path.join('-')}`;
}

/** `cssVar('color.bg.canvas')` -> `var(--gyde-color-bg-canvas)`. */
export function cssVar(dottedPath: string): string {
  return `var(${cssVarName(dottedPath.split('.'))})`;
}

function resolveValue(
  token: Token,
  byName: Map<string, Token>,
  chain: readonly string[] = [],
): string | number {
  const target = aliasTarget(token.value);
  if (target === undefined) {
    return token.value;
  }
  if (chain.includes(target)) {
    throw new Error(`Alias cycle: ${[...chain, target].join(' -> ')}`);
  }
  const next = byName.get(target);
  if (!next) {
    throw new Error(`Token "${token.path.join('.')}" references unknown token {${target}}`);
  }
  return resolveValue(next, byName, [...chain, target]);
}

/** Flat map of token name -> final literal value (aliases resolved). Throws on broken aliases. */
export function resolveTokens(tokens: readonly Token[]): Record<string, string | number> {
  const byName = new Map(tokens.map((token) => [token.path.join('.'), token]));
  return Object.fromEntries(
    tokens.map((token) => [token.path.join('.'), resolveValue(token, byName)]),
  );
}

/**
 * CSS custom properties. Aliases stay as `var()` references, so remapping a palette value (or the
 * semantic layer, for a dark theme) updates everything that depends on it.
 */
export function toCss(tokens: readonly Token[]): string {
  resolveTokens(tokens); // fail the build on a broken alias

  const declarations = tokens.map((token) => {
    const target = aliasTarget(token.value);
    const value = target === undefined ? String(token.value) : cssVar(target);
    return `  ${cssVarName(token.path)}: ${value};`;
  });

  const reducedMotion = tokens
    .filter((token) => token.path[0] === 'motion' && token.path[1] === 'duration')
    .map((token) => `    ${cssVarName(token.path)}: 0.01ms;`);

  return [
    '/* Generated by @gyde/design-tokens. Do not edit: change packages/design-tokens/tokens/*.json */',
    ':root {',
    ...declarations,
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    ...reducedMotion,
    '  }',
    '}',
    '',
  ].join('\n');
}

export function toJson(tokens: readonly Token[]): string {
  return `${JSON.stringify(resolveTokens(tokens), null, 2)}\n`;
}
